version: '3.7'
services:
  elk:
    image: sebp/elk
    container_name: elk
    restart: always
    ports:
      - '5601:5601'
      - '9200:9200'
      - '5044:5044'
      - '12201:12201/udp'
    volumes:
      - './conf/logstash:/etc/logstash/conf.d'
    environment:
      - ES_HEAP_SIZE=128M
      - LS_HEAP_SIZE=128M
    deploy:
      resources:
        limits:
          memory: 800M
    healthcheck:
      test: ['CMD-SHELL', 'curl --fail localhost:9200/_cluster/health || kill 1']
      interval: 60s
# docker-compose --compatibility up -d
