name: app

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [13.x]
        docker-repository: [powerfulyang/powerfulyang.com]
    steps:
      - uses: actions/checkout@v2
      - name: install canvas
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm install
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Dockerize
        id: dockerize
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ matrix.docker-repository }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'latest'
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: '-avz'
          SOURCE: 'powerfulyang.com.yml'
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: /root/app/powerfulyang.com/
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            docker pull ${{ matrix.docker-repository }}
            cd /root/app/powerfulyang.com
            docker-compose -f powerfulyang.com.yml up -d
