name: prod

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: SENTRY
    strategy:
      matrix:
        docker-repository: [powerfulyang/powerfulyang.com]
    steps:
      - uses: actions/checkout@v3
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@v4
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        with:
          name: ${{ matrix.docker-repository }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'latest'
          buildargs: SENTRY_AUTH_TOKEN
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            docker pull ${{ matrix.docker-repository }}
            cd ~/applications
            docker-compose up -d --force-recreate powerfulyang.com
            docker image prune -a -f
